### ISSUE TITLE
Document example with real world data

### ISSUE THREAD

**Issue by peterjc** [DecodeGenetics/chopBAI#10]
The README file just has a generic example assuming files `sequence.bam` and `sequence.bam.bai` in the current directory. It would be helpful to document a real world example where chopBAI is expected to be useful - perhaps something from the 1000 Genomes Project, or an excerpt of the full dataset used but not described in the preprint?

The preprint http://biorxiv.org/content/early/2015/11/06/030825 talks about typical (human) BAI files of 10Mb [sic, see below], and Figure 1 plots data from a specific but unspecified example dataset - presumably _human_ chromosome one. The discussion reports "_With chopBAI’s preprocessing,  the I/O imposed by BAM index files in the analysis of 10 Kbp regions of 10,000 BAM files can be reduced
from 93 Gb to 4.5 Gb per job_", again presumably the same unspecified multiple-individual human data set.

P.S. The preprint could be be misusing the abbreviations Gb and Mb (gigabit and megabit) rather than GB and MB (gigabyte and megabytes). For network IO using bits rather than bytes is (unfortunately) common, but for file size on disk mega or gigabytes is normal, likewise hard drive IO is usually measured in megabytes/second (MB/s).

**Comment by bkehr** [comment]
Regarding your comments about the preprint:

Thanks for pointing out the Gb/GB problem. We will correct this in future versions.

The entire results section of the preprint including Figure 1 refers to a bamfile described in the beginning of the section: _"To evaluate the gain of preprocessing BAM indices with chopBAI we indexed a 62 Gb BAM file containing reads from an Icelander sequenced   at   30-fold   coverage   on   a   HiSeq X Ten   sequencing machine and aligned with BWA-MEM (Li, 2013) to GRCh38. The complete BAM index is 8.8 Mb in size [...]"_

The caption of Figure 1 specifies this further: _"Averages  over  all intervals  tiling  chromosome  1  (10 Mbp  and  1 Mbp)  or  all  intervals  tiling chr1:60,000,000-70,000,000 (100 Kbp, 10 Kbp, 1 Kbp) are shown."_

The bamfile was randomly chosen from a large data set ([Gudbjartsson et al., 2015](http://www.nature.com/ng/journal/v47/n5/full/ng.3247.html) describes a subset of it), which is not publicly available as it is protected by Icelandic law. However, it is a typical 30x human sequencing data set and the results reflect what I/O reduction to expect on this type of data. The sentence you cite from the discussion is based on the result that we _"observe a  95 %  reduction  in  the  total  data  read  for  10 Kbp  regions,  from 9.3 Mb  for  the  full  index  to  450 Kb  for  the  reduced  index"_ for this specific bamfile and only multiplies the 9.3 MB as well as 450 KB by 10,000.

**Comment by peterjc** [comment]
Clearly I didn't make the connection with the Icelandic sequence, sorry about that.

If you can find a similar but public dataset to point users to in the tool documentation as a real world example that would be ideal.

**Comment by peterjc** [comment]
Lovely - even down to explaining one way to measure the performance gains :+1:
