### ISSUE TITLE
Fails to accepts valid samtools style regions

### ISSUE THREAD

**Issue by peterjc** [DecodeGenetics/chopBAI#2]
chopBAI fails to follow the convention long defined in samtools for how to specify a region, e.g. from samtools 0.1.18:

```
$ samtools view --help
...
  4. A region should be presented in one of the following formats:
     `chr1', `chr2:1,000' and `chr3:1000-2,000'. When a region is
     specified, the input alignment file must be an indexed BAM file.
...
```

or samtools 1.2,

```
$ samtools view --help
...
  5. A region should be presented in one of the following formats:
     `chr1', `chr2:1,000' and `chr3:1000-2,000'. When a region is
     specified, the input alignment file must be a sorted and indexed
     alignment (BAM/CRAM) file.
...
```

This is currently implemented via htslib, see https://github.com/samtools/htslib/blob/develop/hts.c#L1877 - allowed syntax is `reference`, `reference:begin` and `reference:begin-end` and comma separators are allowed in the coordinates.

Example:

```
$ samtools idxstats example_bam_file.bam
chr1    1575    1446    18
chr2    1584    1789    17
*   0   0   0
$ ./chopBAI example_bam_file.bam chr1 chr2
ERROR: Could not parse region 0: chr1
       Please specify region in format chr:beg-end.
```

Note that chopBAI also fails to accept comma thousand separators:

```
$ ./chopBAI example_bam_file.bam chr1:1-1,575 chr2:1-1,584
ERROR: Could not parse region 0: chr1:1-1,575
       Please specify region in format chr:beg-end.
```

Workaround:

```
$ ./chopBAI example_bam_file.bam chr1:1-1575 chr2:1-1584
```

**Comment by peterjc** [comment]
As an aside, it is a failing of both the chopBAI and samtools documentation to explain if the begin and end coordinates are open or closed (or zero or one based). This is particularly noticeable with chopBAI if you want to chop per reference as (currently) it forces you to include the beginning and end values. Should I be using:

```
$ ./chopBAI example_bam_file.bam chr1:1-1575 chr2:1-1584
```

or:

```
$ ./chopBAI example_bam_file.bam chr1:0-1575 chr2:0-1584
```

as a workaround for splitting by reference:

```
$ ./chopBAI example_bam_file.bam chr1 chr2
```

**Comment by pmelsted** [comment]
Regions can now be specified as samtools and the --help specifies that these are 1-based closed intervals.

**Comment by peterjc** [comment]
Thank you - I imagine that splitting by reference would be a common use case, and I'm pleased to see that the region name is used as given as the folder name (e.g. just "chr1/" rather than filling in the actual length or worse a maximum length).
